#!/bin/bash 

tagged=0
if [ $# -eq 1 ] ; then
    tag=_$1
    tagged=1
fi

make clean 
make -j 4
cd O.linux-x86_64
if [ $tagged -eq 1 ] ; then
    mv elegant elegant$tag
    installBeta elegant$tag
else
    installBeta elegant
fi
cd ..

make clean 
make -j 4 Pelegant
cd O.linux-x86_64
if [ $tagged -eq 1 ] ; then 
    mv Pelegant Pelegant$tag
    installBeta Pelegant$tag
else
    installBeta Pelegant
fi
cd ..

make clean 
