#!/bin/bash

tagA=(R T)
wildA=(R??* T???*)
thresA=(1e-12 1e-16)

for index in ${!tagA[@]} ; do 
    tag=${tagA[$index]}
    wild=${wildA[$index]}
    thres=${thresA[$index]}
    sddsxref lgbendMatrix.mat ggeMatrix.mat -pipe=out -take=$wild -edit=col,*,ei/Ref/ \
	| sddsconvert -pipe -retain=col,${wild} \
	| sddsconvert -pipe -delete=col,R55*,R6*,T6* \
	| sddsprocess -pipe \
	-define=col,%sAbs,"%s abs",select=*Ref \
	-define=col,deltaAbs%s,"%s %sRef - abs",select=*Ref,edit=%/Ref// \
	-define=col,deltaFrac%s,"deltaAbs%s %sRef abs 1e-16 + / abs",select=[RT]*Ref,edit=%/Ref// \
	-define=col,logDeltaFrac%s,"deltaAbs%s %sRef abs 1e-16 + / abs log",select=[RT]*Ref,edit=%/Ref// \
	| sddsconvert -pipe -retain=col,log*,delta*,*RefAbs \
	| sddsconvert -pipe -delete=col,*[TR]6* \
	| sddscollect -pipe -collect=prefix=deltaFrac -collect=prefix=logDeltaFrac \
	-collect=prefix=deltaAbs -collect=suffix=RefAbs \
	| sddssort -pipe -column=logDeltaFrac,decr \
	| sddsprocess -pipe=in ${tag}-matComp.sdds -filter=col,RefAbs,$thres,1e300 \
	'-redefine=col,logDeltaFrac,logDeltaFrac,symbol=log$b10$n($gD$r'${tag}/${tag}')'
    
    sddsplot  -fixfont=xlabel=0.025,ylabel=0.025,title=0.025,xticks=0.025,yticks=0.025 \
	-graph=sym,vary=sub,fill,scale=2 -order=temp  \
	-col=RefAbs,deltaAbs ${tag}-matComp.sdds \
	-intensitybar=xadjust=50,unitsize=2 \
	-xlabel="Reference value" -ylabel="Absolute error" \
	-split=col=logDeltaFrac -mode=loglog -title="Comparison of $tag matrix elements"
done

