#!/usr/bin/tclsh

# Script to compute core slice emittance from elegant beam file output data
# X. Dong, ANL
# $Log: not supported by cvs2svn $ 
#

if { $argc < 1 || $argc > 2 } {
    puts "usage: $argv0 inputFile \[nSlice\]"
} else {
    set rootname [lindex $argv 0]
    set nslice 30
    if { $argc == 2 } {
	set nslice [lindex $argv 1]
    }

    set charge [exec sdds2stream -par=Charge $rootname]
    #puts "bunch charge is [expr $charge*1e12] pC"

    exec sddsanalyzebeam $rootname $rootname.ana
    #set results [exec sdds2stream $rootname.ana -col=enx,eny,Sdelta,St,pAverage]
    #set Sdelta [lindex $results 2]
    #set St [lindex $results 3]
    #set pAverage [lindex $results 4]
    #set Ek [expr (sqrt(pow($pAverage,2)+1)-1)*0.51099906]
    #puts "beam energy is $Ek MeV"
    #puts "energy spread is [expr $Ek*$Sdelta] MeV"
    #puts "rms bunch length is [expr $St*1e12] ps"


    set nrows [exec sdds2stream -col=x $rootname | wc -l]

    set betax [exec sdds2stream $rootname.ana -col=betax]
    set alphax [exec sdds2stream $rootname.ana -col=alphax]
    set gammax [expr (1+$alphax*$alphax)/$betax]
    set betay [exec sdds2stream $rootname.ana -col=betay]
    set alphay [exec sdds2stream $rootname.ana -col=alphay]
    set gammay [expr (1+$alphay*$alphay)/$betay]

    exec sddsprocess $rootname -pipe=out \
	"-define=col,CSx,$gammax x sqr * 2 $alphax * x * xp * + $betax xp sqr * +" \
	"-define=col,CSy,$gammay y sqr * 2 $alphay * y * yp * + $betay yp sqr * +" \
	"-define=col,A,CSx sqr CSy sqr + sqrt" \
        -delete=col,dt \
	| sddssort -pipe=in $rootname.sorted.sdds \
	-col=A,increasing


    set list [list 8000 9000 9500 10000]
    set w1 10
    set w2 21
    set sep +-[string repeat - $w1]-+-[string repeat - $w2]-+-[string repeat - $w2]-+
    puts $sep
    puts [format "| %-*s | %-*s | %-*s |" $w1 "Percentage" $w2 "Normalized emittanc x" $w2 "Normalized emittanc y"]
    puts [format "| %-*s | %-*s | %-*s |" $w1 "          " $w2 "    (pi mm-mrad )    " $w2 "    (pi mm-mrad )    "]
    puts $sep


    foreach n $list {
	set keep [expr $n*$nrows/10000]
	set percentage [format "%3d%%" [expr $n/100]]
	exec sddsprocess $rootname.sorted.sdds -pipe=out \
	    -clip=$keep,0,invert \
	    -process=t,average,tmean \
	    "-define=col,dt,t tmean -" \
	    -process=dt,maximum,tmax \
	    -process=dt,minimum,tmin \
	    | sddssort -pipe=in $rootname.xxp.sdds \
	    -col=dt,increasing

	exec sddsanalyzebeam $rootname.xxp.sdds $rootname.xxp.sdds.ana
	set results [exec sdds2stream $rootname.xxp.sdds.ana -col=enx,eny]
	set enx [lindex $results 0]
	set eny [lindex $results 1]
	#puts "$percentage [expr $enx*1e6] [expr $eny*1e6]"
	puts [format "| %*s | %-*s | %-*s |" $w1 $percentage $w2 [expr $enx*1e6] $w2 [expr $eny*1e6]]

	set tmax [exec sdds2stream $rootname.xxp.sdds -par=tmax]
	set tmin [exec sdds2stream $rootname.xxp.sdds -par=tmin]
	set stepsize [expr ($tmax-$tmin)/($nslice-1)]
	exec sddsbreak $rootname.xxp.sdds -pipe=out \
	    -changeOf=dt,amount=$stepsize,base=$tmin \
	    | sddsprocess -pipe=in,out \
	    -process=dt,average,dtmean \
	    "-redefine=par,dtmean,dtmean 1e12 *,units=ps,symbol=t" \
	    "-define=par,I,n_rows $charge * $nrows / $stepsize /,units=A" \
	    | sddsanalyzebeam -pipe=in ana$n.sdds
	catch {exec sddsprocess ana$n.sdds -print=par,percentage,$percentage} warning

	file delete -force $rootname.xxp.sdds $rootname.xxp.sdds.ana
    }
    puts $sep
    file delete -force $rootname.sorted.sdds

    exec sddscombine -pipe=out ana10000.sdds ana9500.sdds ana9000.sdds ana8000.sdds \
	| sddsprocess -pipe=in $rootname.slice \
	"-redefine=col,enx,enx 1e6 *,units=\$gp\$r mrad mm,symbol=\$ge\$r\$an\$h\$h\$bx;rms\$n" \
	"-redefine=col,eny,eny 1e6 *,units=\$gp\$r mrad mm,symbol=\$ge\$r\$an\$h\$h\$by;rms\$n"

    exec sddsplot -thick=1 -line=0,thick=2 -col=dtmean,enx -graph=line,vary $rootname.slice -split=page -tickSettings=grid -legend=par=percentage &
    exec sddsplot -thick=1 -line=0,thick=2 -col=dtmean,eny -graph=line,vary $rootname.slice -split=page -tickSettings=grid -legend=par=percentage &
    exec sddsplot -thick=1 -line=0,thick=2 -col=dtmean,I   -graph=line,vary $rootname.slice -split=page -tickSettings=grid -legend=par=percentage &

    after 3000
    file delete -force $rootname.ana ana10000.sdds ana9500.sdds ana9000.sdds ana8000.sdds ana10000.sdds~ ana9500.sdds~ ana9000.sdds~ ana8000.sdds~ $rootname.slice $rootname.slice~

}