#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

if {![info exists env(OAG_TOP_DIR)] || [string length $env(OAG_TOP_DIR)]==0} {
    set env(OAG_TOP_DIR) /usr/local
}
set auto_path [linsert $auto_path 0  $env(OAG_TOP_DIR)/oag/apps/lib/$env(HOST_ARCH)]

APSStandardSetup

set usage {usage: calculateTrapping -twiss <filename> -superPeriods <number> -kappa <ratio> -output <filename> -current <mA> -bunches <number> }
set twiss ""
set superPeriods 0
set kappa -1
set bunches 0
set current 0
set output ""
set args $argv
if {[APSStrictParseArguments {twiss superPeriods output bunches current kappa}] || ![string length $twiss] || ![string length $output] || \
   [expr $bunches<=0] || [expr $current<=0] || [expr $kappa<=0] || [expr $superPeriods<=0]} {
    return -code error "$usage"
}

if ![file exists $twiss] {
   return -code error "not found: $twiss"
}
if [file exists $output] {
   return -code error "in use: $output"
}

exec sddssort $twiss -pipe=out -column=s -unique \
    | sddsprocess -pipe \
    "-define=parameter,kappa,$kappa" \
    "-define=parameter,ex,ex0 1 kappa Jy * Jx / + /,units=m" \
    "-define=parameter,ey,ex kappa *,units=m" \
    "-define=column,Sx,ex betax * Sdelta0 etax * sqr + sqrt,units=m" \
    "-define=column,Sy,ey betay * Sdelta0 etay * sqr + sqrt,units=m" \
     "-define=parameter,current,$current,type=double,units=mA" \
     "-define=parameter,bunches,$bunches,type=long" \
     -process=s,max,sMax \
    -define=parameter,superPeriods,$superPeriods,type=short \
    "-define=parameter,C,sMax superPeriods *,units=m" \
     "-define=parameter,T0,C c_mks /,units=s" \
     "-define=parameter,Ne,current 1e3 / T0 * e_mks / bunches /" \
     "-define=parameter,Sb,C bunches /" \
     "-define=parameter,rp,re_mks me_mks * mp_mks /" \
     "-define=column,Acrit,Ne rp * Sb * 2 / Sx Sy 2 minn / Sx Sy + /" \
    -process=Acrit,min,%sMin \
    "-define=column,sizeRatio,Sy abs Sx abs 1e-16 + /" \
    "-define=column,H2Trapped,Acrit 2 > ? 0 : 1 $ " \
    "-define=column,CH4Trapped,Acrit 16 > ? 0 : 1 $ " \
    "-define=column,H2OTrapped,Acrit 18  > ? 0 : 1 $ " \
    "-define=column,COTrapped,Acrit 28 > ? 0 : 1 $ " \
    "-define=column,CO2Trapped,Acrit 44 > ? 0 : 1 $ " \
    | sddsprocess -pipe -process=*Trapped,integ,%sInteg,functionOf=s -process=sizeRatio,integ,%sInteg,functionOf=s \
    | sddsprocess -pipe "-define=parameter,%sFraction,%sInteg sMax /,select=*TrappedInteg,edit=%/Integ//" \
    "-define=parameter,sizeRatioAve,sizeRatioInteg sMax /" \
    | sddsconvert -pipe=in $output -delete=parameter,*TrappedInteg 

