#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

if {![info exists env(OAG_TOP_DIR)] || [string length $env(OAG_TOP_DIR)]==0} {
    set env(OAG_TOP_DIR) /usr/local
}
set auto_path [linsert $auto_path 0  $env(OAG_TOP_DIR)/oag/apps/lib/$env(HOST_ARCH)]

APSStandardSetup

set usage {usage: LFBFirSetup -twiss <filename> -harmonic <number>(1296) -voltage <MV>(9.0) -terms <number>(30) -interval <turns>(1) -name <string> -output <filename>}
set twiss ""
set harmonic 1296
set voltage 9.0
set output ""
set name ""
set terms 30
set interval 1
set args $argv
if {[APSStrictParseArguments {twiss harmonic voltage name output terms interval}] || ![string length $twiss] || ![string length $output] || ![string length $name]} {
    return -code error "$usage"
}

if ![file exists $twiss] {
   return -code error "not found: $twiss"
}
if [file exists $output] {
   return -code error "in use: $output"
}

set C [exec sddsprocess $twiss -pipe=out -process=s,max,sMax | sdds2stream -pipe -parameter=sMax]
set E0 [expr [exec sdds2stream -parameter=pCentral $twiss]*0.51099906]
set alphac [exec sdds2stream -parameter=alphac $twiss]
set U0 [exec sdds2stream -parameter=U0 $twiss]
set frf [exec sddsprocess $twiss -pipe=out -process=s,max,sMax "-define=param,frf,c_mks pCentral beta.p * $harmonic * sMax /" | sdds2stream -pipe -parameter=frf]

set pi [expr 4*atan(1)]
set phis [expr $pi-asin($U0/$voltage)]
puts stderr "phis: [expr $phis*180/$pi] deg"

set k [expr 2*$pi*$harmonic/$C]
set Vt [expr $voltage/$E0*cos($phis)]

set mus [expr acos(1 + 2*$pi*$alphac*$harmonic*$Vt/2)]
puts stderr "nus: [expr $mus/(2*$pi)]"

set betaz [expr 2*$pi*$alphac*$harmonic/sin($mus)]
puts stderr "betaz: $betaz"

set sum1 0.0
set sum2 0.0
for {set m 1} {$m<$terms} {incr m} {
    set phi [expr $interval*$m*$mus]
    set sum1 [expr $sum1+sin($phi)*cos($phi)]
    set sum2 [expr $sum2+sin($phi)*sin($phi)]
}
set sum2 [expr $sum2*$betaz]

exec sddssequence -pipe=out -define=m,type=long -sequence=begin=0,n=$terms,delta=1 \
     | sddsprocess -pipe=in $output.1 \
     "-define=parameter,mus,$mus" \
     "-define=parameter,denominator,$sum2" \
     "-print=column,ElementName,${name}DRIVER" \
     "-print=column,ElementParameter,A%ld,m" \
     "-define=column,ParameterValue,m 0 == ? $sum1 : m $interval * mus * sin chs $ denominator /"

exec sddsmakedataset $output.2 \
     -column=ElementName,type=string -data=${name}DRIVER,${name}PICKUP \
     -column=ElementParameter,type=string -data=UPDATE_INTERVAL,REFERENCE_FREQUENCY \
     -column=ParameterValue,type=double -data=$interval,$frf \
     -column=m,type=long -data=-1,-1

exec sddssequence -pipe=out -define=m,type=long -seq=begin=0,end=29,delta=1 \
    | sddsprocess -pipe=in $output.3 \
    "-print=column,ElementName,${name}PICKUP" \
    "-print=column,ElementParameter,A%ld,m"  \
    "-define=column,ParameterValue,i_row 0 == ? 1 : 0 $ " 

exec sddscombine $output.1 $output.2 $output.3 -merge $output
file delete $output.1 $output.2 $output.3
