#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

if {![info exists env(OAG_TOP_DIR)]} { set env(OAG_TOP_DIR) /usr/local }
set auto_path [linsert $auto_path 0  $env(OAG_TOP_DIR)/oag/apps/lib/$env(HOST_ARCH)]

APSStandardSetup

set usage {usage: prepareForTAPAs -input <twissFilename> [-output <filename>] -nCells <number> -name <string>\nThe twiss file should be from twiss_output for the full ring with matched=1 and radiation_integrals=1. Setting nCells=0 indicates that TAPAs should not allow scaling with the number of cells.}

set input ""
set output ""
set nCells -1
set name ""
set args $argv
if {[APSStrictParseArguments {input nCells name}] || ![string length $input] || ![string length $name] || $nCells<0} {
    return -code error "$usage"
}

if ![file exists $input] {
   return -code error "not found: $input"
}

if ![string length $output] {
   set output [file rootname $input].tapas
}
if [file exists $output] {
   return -code error "in use: $output"
}

exec sddsprocess $input -pipe=out \
     -process=s,max,sMax \
     -print=parameter,Name,$name \
     -define=parameter,nCells,$nCells,type=long \
     | sddscollapse -pipe=in $output

