#!/bin/bash

if [ $# -ne 4 ] ; then 
    echo "usage: wake2impedance <wakeFile> <timeName> <WName> <impedanceFile>"
    exit 1
fi

wake=$1
tName=$2
WName=$3
imped=$4

sddsfft $wake -pipe=out -col=$tName,$WName -full -nowarning \
    | sddsprocess -pipe=in $imped \
    "-define=col,ZReal,RealFFT$WName fftFrequencySpacing / 2 /,units=V/C" \
    "-define=col,ZImag,ImagFFT$WName fftFrequencySpacing / 2 /,units=V/C" \
