#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  $env(OAG_TOP_DIR)/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 $env(OAG_TOP_DIR)/oag/lib_patch/$env(HOST_ARCH)]
APSStandardSetup

set usage {usage: computeLifetime -rootname <string> [-current <mA>(100)] [-bunches <number>(24)] [-coupling <value>(0.01)] [-deltaLimit <percent>(2.35)] [-sigmaz <mm>]}
set rootname ""
set coupling 0.01
set current 100.0
set bunches 24
set sigmaz 10.0
set deltaLimit 2.35
set args $argv
if {[APSStrictParseArguments {rootname current bunches coupling deltaLimit sigmaz}] || ![string length $rootname]} {
    return -code error "$usage"
}

if ![file exists ${rootname}.mmap] {
    puts stderr "not found: ${rootname}MomentumAperture.mmap"
}
if ![file exists ${rootname}.twi] {
    puts stderr "not found: ${rootname}Moments.twi"
}

exec sddsprocess $rootname.mmap $rootname.mmapn -filter=col,direction,-1,-1 \
    -define=column,deltaNegative,delta
exec sddsprocess $rootname.mmap $rootname.mmapp -filter=col,direction,1,1 \
    -define=column,deltaPositive,delta
exec sddsxref  $rootname.mmapn  $rootname.mmapp -pipe=out -take=* \
    | sddssort -pipe -column=s \
    | sddsconvert -pipe=in $rootname.mmap0 -retain=col,s,ElementName,delta????tive

file delete -force  $rootname.mmapn  $rootname.mmapp

# Figure out how many sectors are covered by the LMA data
set circumference [exec sddsprocess $rootname.twi -pipe=out -process=s,max,%sMax | sdds2stream -pipe -parameter=sMax]
set sMax [exec sddsprocess $rootname.mmap -pipe=out -process=s,max,sMax | sdds2stream -pipe -parameter=sMax]
set number [expr int($circumference/$sMax+0.5)]
if $number!=1 {
    eval exec sddscombine [APSReplicateItem -item $rootname.mmap0 -number $number] -pipe=out \
	| sddsprocess -pipe "{-redefine=col,s,s i_page 1 - $sMax * +,units=m}" \
	| sddscombine -pipe -merge \
	| sddsprocess -pipe=in $rootname.mmapxt -filter=col,s,0,$circumference
    # $rootname.mmapxt now contains the LMA for the full ring, created by replicating the data for $msectors sectors
    # a sufficient number of times 
    set mmapFile $rootname.mmapxt
} else {
    # $rootname.mmap is for the whole ring already
    set mmapFile $rootname.mmap0
}

set bunchCurrent [expr $current/(1.0*$bunches)]
set charge [expr $bunchCurrent*($circumference/2.9979e8)*1e6]

set dataList [exec sdds2stream -parameter=ex0,Sdelta0 $rootname.twi]
APSSetVarsFromList -valueList $dataList -variableList [list ex0 Sdelta0]

exec touschekLifetime $rootname.ltime -twiss=${rootname}.twi  -aperture=$mmapFile \
      -coupling=$coupling -emitxInput=$ex0 -deltaInput=$Sdelta0 -charge=$charge -length=$sigmaz \
      -deltaLimit=$deltaLimit -ignoreMismatch


