#!/bin/bash 

if [ "$1" = "" ] ; then 
    echo "usage: showBest <rootname>"
    exit 1
fi
if [[  ! ( -e $1.best ) ]] ; then
    echo "no files found"
    exit 1
fi

plot1=""
plot2=""
for run in `sddsprocess $1.sort -pipe=out -filter=col,Rank,1,1 | sdds2stream -pipe -column=runName` ; do 
    plot1="$plot1$run.aper "
    plot2="$plot2$run.mmap "
done

sddsplot -layout=1,2 -filename -groupby=fileindex,request -sep=request -filename \
	 -column=xClipped,yClipped -same -graph=sym,fill,con $plot1 \
	 -column=s,delta -same -graph=sym $plot2

