#!/bin/bash

n=9
A=1.5e-3
da=`rpnl $A $n 1 - /`

# Vary skew quads in straights (SQS) with nux-nuy harmonic
sddssequence -pipe=out -define=Sector,type=long -repeat=$n -break -sequence=begin=1,end=40,n=40 \
    | sddsxref -pipe aps.twi -leave=* -transfer=parameter,nu? -reuse=page \
    | sddsprocess -pipe=in skewSineNondisp.sdds \
    "-define=parameter,Amplitude,$da i_page 1 - *" \
    "-print=column,ElementName,SQS" \
    "-print=column,ElementParameter,K1" \
    "-define=column,ParameterValue,nux nuy - 0.5 + int Sector * 40 / 2 * pi * sin Amplitude *" \
    "-define=column,ElementOccurence,Sector,type=long" 

A=`rpnl 1.5e-3 1 mult`
da=`rpnl $A $n 1 - /`
# Vary skew quads in dispersive region with 0 harmonic
sddssequence -pipe=out -define=Sector,type=long -repeat=$n -break -sequence=begin=1,end=40,n=40 \
    | sddsxref -pipe aps.twi -leave=* -transfer=parameter,nu? -reuse=page \
    | sddsprocess -pipe=in skewUniformDisp.sdds \
    "-define=parameter,Amplitude,$da i_page 1 - *" \
    "-print=column,ElementName,SQD" \
    "-print=column,ElementParameter,K1" \
    "-define=column,ParameterValue,Amplitude" \
    "-define=column,ElementOccurence,Sector,type=long" 

    
