#!/bin/bash

elegant aps.ele
makeSkewValues
for file in skew*isp.sdds ; do 
    elegant scanSkewMomentsTemplate.ele -macro=rootname=${file/.sdds/Moments},parameters=$file
    n=`sdds2stream -npage=bare $file`
    skip=$((n-1))
    elegant scanSkewTrackTemplate.ele -macro=rootname=${file/.sdds/Track},parameters=$file,skip=$skip
done

for twi in skew*.twi ; do 
    sddsprocess $twi -pipe=out \
        "-define=col,Hx,betax etaxp sqr * 2 alphax * etax * etaxp * + 1 alphax sqr + betax / etax sqr * +,units=m" \
        "-define=col,Hy,betay etayp sqr * 2 alphay * etay * etayp * + 1 alphay sqr + betay / etay sqr * +,units=m" \
        -match=col,ElementType=CSBEND -match=col,ElementName=S2*M \
        | sddsbreak -pipe -gapin=s,amount=1 \
        | sddsprocess -pipe -process=H[xy],integ,%sInteg,functionOf=s \
        | sddscollapse -pipe \
        | sddsbreak -pipe -change=Step \
        | sddsprocess -pipe -process=H*Integ,sum,%sSum -process=I*,last,%s \
        | sddscollapse -pipe \
        | sddsprocess -pipe=in ${twi}proc \
        "-define=col,exApprox,HxIntegSum 38.9 3 pow / 7e3 mev / sqr * I2 / 3.8319e-13 *,units=m" \
        "-define=col,eyApprox,HyIntegSum 38.9 3 pow / 7e3 mev / sqr * I2 / 3.8319e-13 *,units=m" 
done

for mom in skew*Moments.mom ; do 
    sddsprocess $mom -pipe=out \
        "-define=col,etay,s36 s6 sqr / abs,units=m" \
        "-define=col,etayp,s46 s6 sqr / abs,units=m" \
        | sddsprocess -pipe=in ${mom}proc \
        -process=[se]*,first,%sFirstID -process=[se]*,ave,%sAve \
        -process=[se]*,ave,%sIDAve,match=ElementName,value=S2END
done

sddsplot -param=Step,eyIDAve skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
sddsplot -param=Step,s3IDAve skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
sddsplot -param=Step,etayIDAve skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
sddsplot -param=Step,etaypIDAve skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
sddsplot -param=Step,s4IDAve skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
sddsplot -param=Step,e2 skew*.momproc -graph=line,vary -legend=file,edit=Zw%/.momproc// -mode=linlog -clip=1,0
